config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :ladies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lady.rb
class Lady < ApplicationRecord
   validates :name, presence: true, length: { minimum: 2 }
   validates :face, :chest, :abs, :butt, :legs, presence: true 
   validates :face, :chest, :abs, :butt, :legs, numericality: true
   
   belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :ladies, dependent: :destroy       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/ladies_controller.rb
class LadiesController < ApplicationController
 before_action :set_list, only: [:show, :edit, :update, :destroy]
 before_action :authenticate_user!
  
  def index
    @ladies = Lady.all.where(user_id: current_user_id)
  end

  def show
  end

  def new
    @lady = Lady.new
  end
  
  def create
    @lady = Lady.new(lady_params)
    @lady.user = current_user
    
    if @lady.save
      flash[:success] = 'Lady was added successfully!'
      redirect_to action: :index
    else
      flash.now[:error] = 'Try again boss'
      render :new
    end
  end

  def edit
  end
  
  def update
    if @lady.update(lady_params)
      flash[:success] = 'Lady was updated successfully!'
      redirect_to action: :index
    else
      flash.now[:error] = 'Lady was NOT updated successfully!'
      render :edit
    end
  end
  
  def destroy
    @lady.destroy
    flash[:success] = 'Item was successfully destroyed.'
    redirect_to action: :index
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @lady = Lady.find(params[:id])
    end
    
    def current_user_id
      @curent_user_id = current_user.id
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lady_params
      params.require(:lady).permit(:name, :face, :chest, :abs, :butt, :legs)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ladies_helper.rb
module LadiesHelper
end

app/views/home/index.html.erb
<div class="jumbotron jumbotron-fluid spacer text-center">
  <div class="container">
    <h1 class="display-4">Lucky Lady List</h1>
    <p class="lead"></p>
    <a href="/ladies" class="btn btn-secondary btn-lg" tabindex="-1" role="button" aria-disabled="true">Begin</a>
  </div>
</div>

app/views/ladies/_form.html.erb
<div class="row align-items-center">
    <div class="col-md-6 offset-md-3">
        <%= form_for @lady do |f| %>
        <div class="form-group">
          <%= f.label 'Name' %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <h3>Enter Score from 1 to 5</h3>
        <div class="form-group">
          <%= f.label 'Face' %>
          <%= f.text_field :face, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label 'Chest' %>
          <%= f.text_field :chest, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label 'Abs' %>
          <%= f.text_field :abs, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label 'Butt' %>
          <%= f.text_field :butt, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label 'Legs' %>
          <%= f.text_field :legs, class: 'form-control' %>
        </div>
          <%= f.submit "New Lady" %>
        <% end %>
    </div>
</div>

app/views/ladies/edit.html.erb
<h1>Edit Lady</h1>
<%= render 'form' %>

app/views/ladies/index.html.erb
<h1 class="spacer">Ladies</h1>
<table class="table table-responsive-sm table-striped table-dark spacer">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Face</th>
      <th scope="col">Chest</th>
      <th scope="col">Abs</th>
      <th scope="col">Butt</th>
      <th scope="col">Legs</th>
      <th scope="col">Total</th>
      <th scope="col">Show</th>
      <th scope="col">Edit</th>
       <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
      <% @ladies.each do | lady |%>
    <tr>
      <th scope="row"><%= lady.id %></th>
      <td><%= lady.name %></td>
      <td><%= lady.face %></td>
      <td><%= lady.chest %></td>
      <td><%= lady.abs %></td>
      <td><%= lady.butt %></td>
      <td><%= lady.legs %></td>
       <td><%= lady.face + lady.chest + lady.abs + lady.butt + lady.legs %></td>
      <td><%= link_to 'Show', lady_path(lady) %></td>
      <td><%= link_to 'Edit', edit_lady_path(lady)%></td>
      <td><%= link_to 'Delete', lady,  method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>



<%= link_to "New Lady", new_lady_path %>

app/views/ladies/new.html.erb
<h1>New Lady</h1>

<%= render  'form' %>

app/views/ladies/show.html.erb
<div class="row">
    <div class='col-md-6 offset-md-3 spacer'>
      <div class="card" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title">Lucky Lady</h5>
            <h6 class="card-subtitle mb-2 text-muted"><%= @lady.name %></h6>
            <p class="card-text">Face: <%= @lady.face %></p>
            <p class="card-text">Chest: <%= @lady.chest %></p>
            <p class="card-text">Abs: <%= @lady.abs %></p>
            <p class="card-text">Butt: <%= @lady.butt %></p>
            <p class="card-text">Legs: <%= @lady.legs %></p>
            <%= link_to 'Lady List', ladies_path %>
          </div>
        </div>  
    </div>
</div>

<%= link_to "New Lady", new_lady_path %>

app/views/layouts/_messages.html.erb
 <% flash.each do |key, value| %>
   <% key = 'danger' if key == 'error' %>
    <%= content_tag :div, value, class: "alert alert-#{key}" %>
 <% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Playlist</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
         <% if user_signed_in? %>
        <%= link_to "Home", ladies_path, class: 'nav-link' %>
        <% end %>
      </li>
      <li class="nav-item">
         <% if user_signed_in? %>
        <%= link_to "New Lady", new_lady_path, class: 'nav-link' %>
        <% end %>
      </li>
     
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Profile
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <ul>
         <% if user_signed_in? %>
            <li><%= link_to "Edit profile", edit_user_registration_path %></li>
        <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
        <% if user_signed_in? %>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% end %>
        </ul>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ladies</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
  </head>

  <body>
    <div class="container">
       <%= render 'layouts/navbar' %>
       <%= render 'layouts/messages' %>
       <%= yield %>
    </div>
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  </body>
</html>